language: node_js
node_js:
    - "node"
branches:
  only:
    - master
install:
    - npm install
before_script:
  - npm install -g lighthouse
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - npm explore -g lighthouse -- ./lighthouse-core/scripts/download-chrome.sh
  - mv $(npm root -g)/lighthouse/chrome-linux .
  - $LIGHTHOUSE_CHROMIUM_PATH --version
script:
    - echo 'Building https://jacekkosciesza.com'
    - npm run build
    #- npm run serve
    - ./start-server.sh
    #- npm run lighthouse
    - lighthouse --output=json http://localhost:8080 --output-path=./validate/lighthouse.json
    - node lighthouse-check.js ./validate/lighthouse.json
after_success:
    - echo 'Deploying https://jacekkosciesza.com to Firebase'
    - firebase deploy --token=${FIREBASE_API_TOKEN}