language: node_js
node_js:
    - "node"
branches:
  only:
    - master
install:
    - npm install
script:
    - echo 'Building https://jacekkosciesza.com'
    - npm run build
    #- npm run serve
    - ./start-server.sh
    - npm run lighthouse
after_success:
    - echo 'Deploying https://jacekkosciesza.com to Firebase'
    - firebase deploy --token=${FIREBASE_API_TOKEN}